import React from 'react';

const Left = () => {
    return (
        <div className=' text-justify my-3 border-solid border-2 p-3 border-sky-500 '>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima accusantium quo officia commodi maxime inventore error ipsa, ut, corrupti repellat nulla deserunt! Adipisci rerum unde labore eius maiores. Ullam sint labore nam mollitia aliquid, facilis natus? Laborum fugiat, voluptatibus commodi magnam molestiae quibusdam iusto praesentium cum incidunt voluptatem eum modi assumenda, perspiciatis velit facilis. Saepe a totam dolore quam distinctio nihil atque mollitia, dolor ipsam accusantium repellendus sint libero ipsa similique officia ex, iste eius vero quod aperiam dicta eam repellendus sint libero ipsa similique officia ex, iste eius vero quod aperiam dicta eaque! Cupiditate delectus nemo, sunt libero repellat unde dolores! Voluptatem minimanim, error aliquid nam dignissimos sequi dolor iure, odio odit. Laborum eveniet, maiores, placeat in corporis quaerat non accusamus cumque a eum asperiores recusandae officia, iure quidem. Ut soluta magni expedita, fugiat magnamNostrum numquam quidem temporibus laborum maiores velit soluta eaque nulla, veritatis consequuntur distinctio, dolores iusto, perspiciatis sint. Minus quo vel dicta qui eveniet aperiam voluptas doloremque atque explicabo dolor! Illo at velit laudantium culpa pariatur consequatur sequi quaerat eligendi? Ducimus non earum aperiam, exercitationem vel ratione. Quia, architecto! Similique repellendus, maxime, nostrum quia sequi ducimus voluptas est accusantium quaerat unde quas dolorum voluptates beatae, sapiente incidunt cum. Omnis consectetur eaque quibusdam deserunt ullam magni odio modi, rem voluptatem saepe illo sint dignissimos porro cupiditate, incidunt iste sunt a molestias doloribus iusto consequatur quas perspiciatis vitae. Praesentium ab quod modi odit perspiciatis ducimus eaque quibusdami odio modi, rem voluptatem saepe illo sint dignissimos porro cupiditate, incidunt iste sunt a molestias doloribus iusto consequatur quas perspiciatis vitae. Praesentium ab quod modi odit perspiciatis ducimus illum eum consectetur! Quibusdam officiis aspernatur nostrum quisquam voluptatem earum consequatur sint. Quibusdam explicabo eaque fugit corporis odio libero ium consequatur sint. Quibusdam explicabo eaque fugit corporis odio libero ieaque quibusdam deserunt ullam magni odio modi, rem voluptatem saepe illo sint dignissimos porro cupiditate, incidunt iste sunt a molestias doloribus iusto consequatur quas perspiciatis vitae. Praesentium ab quod modi odit perspiciatis ducimus illum eum consectetur! Quibusdam officiis aspernatur nostrum quisquam voluptatem earum consequatur sint. Quibusdam explicabo eaque fugit corporis odio libero id.</p>
        </div>
    );
};

export default Left;